apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/load-generator-python
patches:
  - path: ./patches/Deployment.yaml
    target:
      kind: Deployment
      name: load-generator-python-deployment
      version: v1
      group: apps
