apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-node-ingress
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`learn-k8s-kayn.work.gd`) && PathPrefix(`/api/node`)
      kind: Rule
      services:
        - kind: Service
          name: api-node-service
          port: 3000
          scheme: http
      middlewares:
        - name: traefik-middleware-stripprefix
