apiVersion: v1
kind: Service
metadata:
  name: client-react-service
  namespace: demo-app
spec:
  selector:
    app: client-react
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
