apiVersion: v1
kind: Service
metadata:
  name: api-golang-service
  namespace: demo-app
spec:
  selector:
    app: api-golang
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000 # Must match containerPort in Deployment.yaml
      protocol: TCP
