apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-golang-deployment
  namespace: demo-app
spec:
  replicas: 3 #base-replicas
  template:
    spec:
      containers:
        - name: api-golang
          image: hkdarealest/devops-directive-docker-course-api-golang:0.3.0 #base-version
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "250m"
