apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-stripprefix
  namespace: demo-app
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /api/golang
      - /api/node
