apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
  - ../../base/api-node
patches:
  - path: ./patches/Deployment.yaml
  - path: ./patches/IngressRoute.replace-host.yaml
    target:
      kind: IngressRoute
      name: api-node-ingress
      namespace: demo-app
      version: v1alpha1
      group: traefik.containo.us
