---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-node-secret
  namespace: demo-app
spec:
  encryptedData:
    DATABASE_URL: AgBWpPpOlcspRfpWn67w+bjdoimxqvNdDYTFLRIzRDpAuwwfEIZLZvp/eXDU03cAynbU9RuXbUcDhoquSr3W+hx/AYFA0K53X5j7E1JKvnwDT6L8dALw5Awp5DsPlQBsyfRQ1qBsOg/o5NfNB2sHn8HVWxerP0c/kum67TYnmMTH4nSkXGuY2YNQX/k/Z0X/LTskvZnIN4S0b/h5BCn6MvJEQ0AcLug8usfyMtnIl+fKKzUvfqqp55gQcH5SZDXIFBVa46zlXx71n1yqHoKa42omQoLH1EixyfLpCDabAIt1Q6tDUAVdhv7S+NW0XW/JIH6Fs7ED/KHZzPXeELDi8H18rPuiHUUktslTN/0uM2TUUDlUpui1B0Jlrck4QcpgUoiN/SPLZ59z90h4rGIMYFY3uw1j3oJ7T5SLdgjHqKoz0B2R1PK1DNiw+bT9jpELVEFIHFCIOh3BU9rsvv75wppXNy5YRXouCUcuJoADLa6xjJ24aZx56i8JUyaNWCM/WZqdnxAe+8zoXY9V1pkkcPWZ4cyauIEeB7sCq5T6NHftqlnCJ7HuInVvkmKwwqgSQmBVRP5G3vsS9csFxc+vcO6Rsa9wXlTddqnKrGDxXn6zk+ur/Bikz3QsZ+GmKkr3rYINcyfIkZcAnR38UzKhrzm2hS8KUJA3OTJvSXwuLzV6XdTttn5+1+baTVz2RrBII3tFIOh1YnVIe2GQdgYQN6a7A8lDvToWhXqfuw14gF902nvxdJOnXd7J0fTcFoGuV3xbfX0ijWF6mqPJ2WQoWCEUzM0bjgbzLhdKohKnaJNqSO2baikp5LnR6T1wIR/g/2W20MGf7FrjYWlUAAigxqDO
  template:
    metadata:
      name: api-node-secret
      namespace: demo-app
    type: Opaque
