apiVersion: v1
kind: Service
metadata:
  name: api-node-service
  namespace: demo-app
spec:
  selector:
    app: api-node
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
