apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-golang-ingress
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - match: #Base path which will be populated  # Host(`learn-k8s-kayn.work.gd`) && PathPrefix(`/api/golang`)
      kind: Rule
      services:
        - kind: Service
          name: api-golang-service
          port: 8000
          scheme: http
      middlewares:
        - name: traefik-middleware-stripprefix
