---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-golang-secret
  namespace: demo-app
spec:
  encryptedData:
    DATABASE_URL: AgB2Acb0X+S2dfbk7CzIW/BDwp+fgUTAQ2ZgBurHNGgDhQ5D5/DqQolA7w16csOPPxjO+advwY4L1VqXbGSmakyPNMSVZNoy+WlBQX8BB1K7a/+6bS2KyezEnpcosnYuVLy/ZcGVFoXlQfivV77OTza1J9DdGbrprIhL1ozLNvXK4sbWqKk9SXCdMB80NNxmLci7anTcS3geofUF/awd+OOzmstDIA8ThSY6AsxqGqKhUk9jahKyFsvCj0ztzAkdNT7qlTwUlB07RpNE845VszqSqs6f8vI3VPPIbKqFAQR3C6eXrPD3MXgx9PU5nbiBenceOigYSbf/03iBsWS2MZ7tksy0khP39lpQxpu4SlaU9Gb9bY38CVE8CFzpI0cx/ZNoA1NWAyr0UwEUGJnEWM2MsR7x/aEj2HAsE4riMW3Zup/PYMk6y/y+FK8zJFlEdxJPdUA/ToLqz65HkUzsDL+129iIktOlR4ZXm+C5llnIUY5syjbCZRx2c06fgSwN0OwlYlQCeH5JtKdiXc6u+7jP4aXEDNbN78GifqV2+iPeC/TMHRluA5ieKA8dgdODErnsnUf9B9IZrWWsUHDF3D+w7Bc/SRnT0Z9OZVUNpzs3itSbzDg/+0J+4XsI2MzMotFv5tkZQ7LIoDn0l5jslJb3Mse6X6ecXDKHqgFuPiyeox2KX6D0AKbDeHoSJLuoU7uE0edfyX2nIGxD7C0mPXK80FhiOMXO7UiASJN2DOj3Q/VSkE1FGP8uw65Ex7pU7HgAZKFYPYydUhqAGVRqHGn36oER3azpyjboaQ4vo26oE6veBXk2Z31BrHiw2O2VjEAYLSO+PE5C6PFPcKD25Tob
  template:
    metadata:
      name: api-golang-secret
      namespace: demo-app
    type: Opaque
