apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app-production
resources:
  - api-golang
  - api-node
  - client-react
  - ../base/traefik-middleware
  - load-generator-python
